### ISSUE TITLE
[Bug]: Cassette Fields?

### ISSUE THREAD

**Issue by Sackboy166** [CommunalHelper/CherryHelper#5]
### Before You Report

- [x] My mods and Everest install are up to date.
- [X] I have recreated the bug with a minimum number of mods installed.

### What platform are you playing on?

Windows 11

### Bug Description

What's up with these? The settings are broken and don't show up, nor can you resize them in the viewport, they don't seem to do anything in-game, and that's probably because the code doesn't exist! I searched for it and it just isn't there, it's just the Lonn and Ahorn files. What's going on here?

### Steps to Reproduce

Place them in the map editor and right click, attempt to resize, or save look at how they don't show up in-game.

**Comment by bigkahuna443** [comment]
You're right, looks like it was a WIP entity that was never actually made. It'll be removed in the next update. Thanks for reporting!
